# <span style="color:#0b486b">  FIT3181/5215: Deep Learning (2024)</span>
***
*CE/Lecturer (Clayton):*  **Dr Trung Le** | trunglm@monash.edu <br/>
*Lecturer (Clayton):* **Prof Dinh Phung** | dinh.phung@monash.edu <br/>
*Lecturer (Malaysia):*  **Dr Arghya Pal** | arghya.pal@monash.edu <br/>
*Lecturer (Malaysia):*  **Dr Lim Chern Hong** | lim.chernhong@monash.edu <br/>  <br/>
*Head Tutor 3181:*  **Miss Vy Vo** |  \[tran.vo@monash.edu \] <br/>
*Head Tutor 5215:*  **Dr Van Nguyen** |  \[van.nguyen1@monash.edu \]

<br/> <br/>
Faculty of Information Technology, Monash University, Australia
***

# Tutorial 1a: Introduction to PyTorch


`Acknowledgement:` This tutorial is developed based on [this Google Colab tutorial](https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb#scrollTo=XFVEgrKhTGfD).

## Importing PyTorch

Let's start by importing PyTorch and checking its version.

In [ ]:
#pip install torch


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
#pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:

#pip install torch --upgrade

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import torch
torch.__version__
import numpy
print(numpy.__version__)


2.1.2


## Introduction to Tensors

First, we create a `scalar` with the value `7`.

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
print(scalar.item())

7


In [ ]:
#pip install numpy --upgrade


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np
print(np.__version__)

2.1.2


We now create an `1D` vector

In [9]:
vector = torch.tensor([1.0,2,3,4])
vector

tensor([1., 2., 3., 4.])

In [10]:
vector.dtype

torch.float32

We create an `2D` tensor or a matrix.

In [11]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
print(f"dim={matrix.ndim}, shape={matrix.shape}")

dim=2, shape=torch.Size([2, 3])


In [13]:
import numpy as np
import torch

# 创建一个 NumPy 数组
npArray = np.array([1, 2, 3, 4])

# 将 NumPy 数组转换为 PyTorch 张量
torchArray = torch.from_numpy(npArray)
print(torchArray)


tensor([1, 2, 3, 4])


In [14]:
print(matrix.numpy())

[[1 2 3]
 [4 5 6]]


In [15]:
print(vector.dtype)

torch.float32


## Create Tensors in PyTorch

### Initialize Random Tensors

In [16]:
randImage = torch.rand(size=(224,224,3))
randImage

tensor([[[5.1009e-01, 7.2349e-01, 5.9725e-02],
         [5.1766e-01, 8.8414e-02, 8.0802e-01],
         [3.9328e-01, 2.2791e-01, 7.0096e-01],
         ...,
         [9.2487e-01, 7.7194e-01, 4.5754e-01],
         [9.0791e-01, 6.6825e-01, 2.4605e-01],
         [4.6075e-02, 5.4331e-01, 7.5524e-01]],

        [[6.4407e-01, 7.8682e-01, 8.6105e-01],
         [4.3533e-02, 4.8809e-01, 7.9932e-01],
         [4.6966e-01, 1.1071e-01, 2.4677e-01],
         ...,
         [8.6177e-01, 5.6061e-01, 1.7173e-01],
         [9.8231e-01, 7.4105e-01, 2.6203e-02],
         [7.8329e-01, 6.7486e-01, 7.1077e-01]],

        [[5.2530e-01, 2.3077e-01, 7.5370e-01],
         [7.3092e-01, 2.1723e-02, 1.1905e-01],
         [7.1045e-01, 1.2369e-01, 3.6610e-01],
         ...,
         [8.1984e-01, 1.5805e-01, 8.7451e-01],
         [1.0061e-01, 6.2223e-01, 5.4406e-01],
         [8.0270e-02, 9.8438e-01, 9.7282e-01]],

        ...,

        [[6.2299e-01, 9.9425e-01, 5.0749e-01],
         [6.3736e-01, 1.3557e-01, 6.0356e-01]

In [17]:
print(f"Shape: {randImage.shape}, ndim = {randImage.ndim}, height= {randImage.shape[0]}, width = {randImage.shape[1]}, depth = {randImage.shape[2]}")

Shape: torch.Size([224, 224, 3]), ndim = 3, height= 224, width = 224, depth = 3


### Create One, Zero Tensors

In [18]:
ones = torch.ones(size= (2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
zeros = torch.zeros(size = (2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones_like = torch.ones_like(zeros)
ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
zeros_like = torch.zeros_like(ones)
zeros_like

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Create a Range and Reshape

In [22]:
aRange = torch.arange(start = 0.1, end = 5.0, step = 0.2)
aRange

tensor([0.1000, 0.3000, 0.5000, 0.7000, 0.9000, 1.1000, 1.3000, 1.5000, 1.7000,
        1.9000, 2.1000, 2.3000, 2.5000, 2.7000, 2.9000, 3.1000, 3.3000, 3.5000,
        3.7000, 3.9000, 4.1000, 4.3000, 4.5000, 4.7000, 4.9000])

In [23]:
matrix = aRange.reshape(shape = (5,5))
matrix

tensor([[0.1000, 0.3000, 0.5000, 0.7000, 0.9000],
        [1.1000, 1.3000, 1.5000, 1.7000, 1.9000],
        [2.1000, 2.3000, 2.5000, 2.7000, 2.9000],
        [3.1000, 3.3000, 3.5000, 3.7000, 3.9000],
        [4.1000, 4.3000, 4.5000, 4.7000, 4.9000]])

### From NumPy Arrays

We first import `numpy` and then create a numpy array.

In [24]:
import numpy as np

In [25]:
npArray = np.arange(1,21, dtype = np.float32)
npArray

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.], dtype=float32)

We reshape the above numpy array to `(5,5)`

In [26]:
npArray = npArray.reshape((5,-1))
npArray

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]], dtype=float32)

We create a torch array or tensor from the numpy array using the method `torch.from_numpy()`.

In [27]:
torchArray = torch.from_numpy(npArray)
torchArray

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

We cast the float Torch tensor to the integer one.

In [28]:
torchArray = torchArray.type(torch.int16)
torchArray

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]], dtype=torch.int16)

In [29]:
print(torchArray.numpy())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types). Some are specific for CPU and some are better for GPU. Getting to know which is which can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`. This is referred to as "32-bit floating point". But there are also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`). And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.


In [30]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [31]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [32]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7792, 0.7557, 0.0662, 0.2026],
        [0.6939, 0.0623, 0.6929, 0.8952],
        [0.8959, 0.1490, 0.5242, 0.0072]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors. A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

### Basic operations

Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).

In [33]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor1 = tensor + 10
tensor1

tensor([11, 12, 13])

In [34]:
# Multiply it by 10
tensor2 = tensor * 10
tensor2

tensor([10, 20, 30])

In [35]:
# Subtract and reassign
tensor3 = tensor - 10
tensor3

tensor([-9, -8, -7])

PyTorch also has a bunch of built-in functions like [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (short for multiplication) and [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) to perform basic operations.

In [36]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

However, it's more common to use the operator symbols like `*` instead of `torch.mul()`

In [37]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.



In [38]:
A = torch.arange(1,7, dtype = torch.float32).reshape((3,-1))
print(f"A={A}\n shape = {A.shape}")

A=tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
 shape = torch.Size([3, 2])


In [39]:
B = torch.rand((2,4))
print(f"B={B}\n shape = {B.shape}")

B=tensor([[0.3200, 0.5454, 0.7643, 0.1485],
        [0.2709, 0.3319, 0.3691, 0.9488]])
 shape = torch.Size([2, 4])


Matrices `A` with the shape $3 \times 2$ and `B` with the shape $2 \times 4$ are compatible in dimension, so we can multiple them.

In [40]:
C1 = torch.matmul(A,B)
C1

tensor([[0.8619, 1.2091, 1.5025, 2.0461],
        [2.0438, 2.9636, 3.7693, 4.2408],
        [3.2257, 4.7182, 6.0360, 6.4355]])

In [41]:
C2 = A.matmul(B)
C2

tensor([[0.8619, 1.2091, 1.5025, 2.0461],
        [2.0438, 2.9636, 3.7693, 4.2408],
        [3.2257, 4.7182, 6.0360, 6.4355]])

In [42]:
C3 = A@B
C3

tensor([[0.8619, 1.2091, 1.5025, 2.0461],
        [2.0438, 2.9636, 3.7693, 4.2408],
        [3.2257, 4.7182, 6.0360, 6.4355]])

`C1`, `C2`, and `C3` must be the same and we assert this.

In [43]:
assert torch.equal(C1,C2)
assert torch.equal(C1,C3)

### One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [46]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

To fix this, we need to transpose `tensor_B` before doing multiplication.

In [47]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Linear Layer

Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `W`.

$$
y = x\cdot W + b
$$


In [48]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Finding the min, max, mean, sum, etc (aggregation)

Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [49]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


 **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with `torch` methods.

In [52]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

You can also find the index of a tensor where the max or minimum occurs with [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [54]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |


In [55]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Let us add an extra dimension with reshape.

In [56]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [57]:
x_reshaped[0][0] =100
print(x_reshaped)
print(x)

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.]])
tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.])


We can also change the view with `torch.view()`.

In [58]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [59]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

NameError: name 'x' is not defined

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()`, (you can remember this as *squeezing* the tensor to only have dimensions over 1).

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the input gets turned into a view with new dims.

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing. If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([ 5, 14])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

**<span style="color:red">Exercise 1</span>:** Write the code to
- Create a random 2D tensor X with dimension [32,10] (i.e., batch size = 32 and #features = 10).
- Create a random weight matrix W with dimension [10,2] and random bias b with dimension [1,2].
- Do the computation y = XW + b and pred_probs = softmax(y).

In [ ]:
#Your answer here
X = torch.rand(32,10)
W = torch.rand(10,2)
b = torch.rand(1,2)
y = X@W + b
pred_probs = torch.nn.functional.softmax(y, dim =1)
print(y)
print(pred_probs)

tensor([[3.9280, 3.7419],
        [4.4760, 3.4386],
        [3.9935, 3.0428],
        [3.1070, 2.9910],
        [4.5176, 3.1744],
        [4.2931, 3.2387],
        [4.1238, 2.5947],
        [3.9920, 2.3232],
        [3.9929, 2.8354],
        [2.5538, 2.6940],
        [3.4423, 2.9238],
        [3.4218, 3.4819],
        [2.3185, 2.0752],
        [3.5383, 2.1712],
        [4.5011, 3.9945],
        [3.2103, 2.8546],
        [4.3674, 2.8571],
        [4.0535, 2.5425],
        [3.5923, 3.3916],
        [4.0700, 3.1735],
        [3.3815, 3.3613],
        [3.9620, 2.8113],
        [3.2280, 1.9424],
        [4.5963, 3.0943],
        [2.4367, 2.1230],
        [3.9404, 3.8905],
        [4.1113, 3.4705],
        [3.2158, 3.2339],
        [3.7316, 3.0438],
        [3.3216, 2.9143],
        [2.7924, 2.9424],
        [3.1873, 2.5137]])
tensor([[0.5464, 0.4536],
        [0.7383, 0.2617],
        [0.7213, 0.2787],
        [0.5290, 0.4710],
        [0.7930, 0.2070],
        [0.7416, 0.2584],
        [0.

----

**The end**